# This dockerfile assumes it is being run with a build context inside ./container. The files in the ADD commands won't be found and will crash the build otherwise)
FROM localdev/mrplotter:latest

ADD ./container/pt-mr-plotter $GOPATH/bin/
ADD ./ $GOPATH/src/github.com/PingThingsIO/pt-mr-plotter 
ADD ./container/entrypoint.sh /entrypoint.sh
RUN chmod a+x /entrypoint.sh
# RUN go get -u github.com/derekparker/delve/cmd/dlv
ENTRYPOINT ["/entrypoint.sh"]
